### ISSUE TITLE
Official release of v4

### ISSUE THREAD

**Issue by gzurbach** [ember-cli-deploy/ember-cli-deploy-s3-index#141]
Hello @lukemelia 

With the recent release of `ember-cli-deploy-s3@4.0.2` using AWS SDK v3, are there any plans to designate `ember-cli-deploy-s3-index@4.0.0` as an official release?

This move would effectively resolve the persistent AWS deprecation warning 🙂

**Comment by lukemelia** [comment]
We had to backtrack on that release because it appears to have been breaking some setups. On the other hand, this repo's changes have been available since August 2023 and were made a major already. So I think I will go ahead and release this version for s3-index.

**Comment by lukemelia** [comment]
Released https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/releases/tag/v4.0.1
