### ISSUE TITLE
Rename ember-cli-deploy-revision-key to ember-cli-deploy-revision-data

### ISSUE THREAD

**Issue by wvteijlingen** [ember-cli-deploy/ember-cli-deploy-s3-index#16]
I copied the package name `ember-cli-deploy-revision-key` from the README, which gave me an old version of the wrong package. This resulted in the s3-index plugin not working correctly.

**Comment by LevelbossMike** [comment]
Sorry for the inconvenience caused and thanks for this issue. :+1:
