### ISSUE TITLE
Get listed on ember-cli-deploy plugins page

### ISSUE THREAD

**Issue by jpaas** [ember-cli-deploy/ember-cli-deploy-s3-index#18]
Thanks for building this! I was thrilled to find it in npm, but we need to get it listed on the plugins page http://ember-cli.github.io/ember-cli-deploy/docs/v0.5.x/plugins-overview/

**Comment by achambers** [comment]
Thanks @jpaas. Feel free to knock together a PR. We're more than happy to accept contributions :)

**Comment by LevelbossMike** [comment]
Thx for this issue! closed via ember-cli/ember-cli-deploy#291
