### ISSUE TITLE
ENOENT when running `ember deploy` with `ember-cli-deploy-s3-index` installed

### ISSUE THREAD

**Issue by nwjsmith** [ember-cli-deploy/ember-cli-deploy-s3-index#21]
After installing `ember-cli-deploy-s3-index`, when I run `ember deploy` I get the following error:

```
Error: ENOENT: no such file or directory, open 'tmp/deploy-dist/**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2}'
Error: ENOENT: no such file or directory, open 'tmp/deploy-dist/**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2}'
    at Error (native)Pipeline aborted
```

My `config/deploy.js`:

``` javascript
/* jshint node: true */

module.exports = function(deployTarget) {
  var s3Credentials = {
    accessKeyId: '...',
    secretAccessKey: '...',
    bucket: '...',
    region: 'us-east-1'
  };
  var ENV = {
    build: { environment: deployTarget },
    s3: s3Credentials,
    's3-index': s3Credentials
  };

  return ENV;
};
```

The other ember-cli-deploy plugins I have installed are:
- ember-cli-deploy-build, 0.1.0
- ember-cli-deploy-manifest, 0.1.0
- ember-cli-deploy-s3, 0.1.0

**Comment by LevelbossMike** [comment]
mmh strange. I'll look into this this afternoon.

**Comment by nwjsmith** [comment]
It might also be worth noting that there are no png, gif, ico, jpg, map, xml, txt, svg, swf, eot, ttf, woff, or woff2 files in my project yet.

**Comment by LevelbossMike** [comment]
I can't reproduce this. What does your package.json look like? The output suggests that no build is happening. Do you really have ember-cli-deploy-build installed?

**Comment by nwjsmith** [comment]
``` json
{
  "name": "flow",
  "version": "0.0.0",
  "description": "Small description for flow goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "2.3.0",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "1.0.0",
    "ember-cli-babel": "5.1.5",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "1.1.0",
    "ember-cli-deploy": "0.5.0",
    "ember-cli-deploy-build": "0.1.0",
    "ember-cli-deploy-manifest": "0.1.0",
    "ember-cli-deploy-s3": "0.1.0",
    "ember-cli-deploy-s3-index": "0.1.0",
    "ember-cli-htmlbars": "1.0.1",
    "ember-cli-htmlbars-inline-precompile": "0.3.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "1.3.1",
    "ember-cli-pretender": "0.5.0",
    "ember-cli-qunit": "1.0.3",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "1.1.0",
    "ember-cli-uglify": "1.2.0",
    "ember-data": "2.1.0",
    "ember-disable-proxy-controllers": "1.0.1",
    "ember-export-application-global": "1.0.5",
    "ember-resolver": "2.0.3"
  }
}
```

**Comment by nwjsmith** [comment]
@LevelbossMike I think I might have identified the problem, no need to waste your time. I'm going to close this and follow up with a PR after I confirm and fix the issue. Thanks for the time you've spent on this.

**Comment by LevelbossMike** [comment]
For other people stumbling over this.

This is caused by the fact that you are using the same object for config options for s3 and s3-index. If you  change to different objects the ember-cli-deploy will behave as expected.

I suppose this has to do how configuration options are read when using `ember-cli-deploy-plugin` as base for your plugins. I'll bring this up in the core team internally. Thx for this issue.

**Comment by seawatts** [comment]
Thanks! that last fix worked for me too @LevelbossMike

**Comment by jaydev** [comment]
I just tried a deploy on a fresh project with essentially the same config setup as @nwjsmith and I got the same error.

My dependencies:

```
"ember-cli-deploy": "0.5.1",
"ember-cli-deploy-build": "0.1.1",
"ember-cli-deploy-gzip": "0.2.1",
"ember-cli-deploy-manifest": "0.1.1",
"ember-cli-deploy-revision-data": "0.1.1",
"ember-cli-deploy-s3": "0.2.1",
"ember-cli-deploy-s3-index": "0.3.1",
```

**Comment by LevelbossMike** [comment]
@jaydev are you sharing a configuration object between the s3 and s3-Index plugin? This still not supported and has yet to be fixed

**Comment by jaydev** [comment]
I was initially sharing the config object, but duplicating the config worked for me.

I guess I commented here because the related issue (https://github.com/ember-cli/ember-cli-deploy/issues/299) has been closed but the problem still exists. Should it be reopened?
