### ISSUE TITLE
Backslashes mess up revision activation on Windows

### ISSUE THREAD

**Issue by SingpointGitHub** [ember-cli-deploy/ember-cli-deploy-s3-index#25]
Plugin fails to activate revisions on S3 when used on Windows environments. I am using Windows 10 x64. When creating a query for S3 the key for identifying filenames on S3 contains backslashes and the process fails with following error:

InvalidArgument: Copy Source must mention the source bucket and key: sourcebucket/sourcekey

For everyone encountering the same issue with version 0.1.0 there is a quick and dirty fix. Edit the file ember-cli-deploy-s3-index/lib/s3.js and replace the following line:

`var copySource  = encodeURIComponent(path.join(bucket, revisionKey);`
with
`var copySource  = encodeURIComponent(path.join(bucket, revisionKey).replace('\\','/'));`

**Comment by carlosgalveias** [comment]
Have the same issue

**Comment by davidbilling** [comment]
That fixed my problem. Hope to see a fix soon.
