### ISSUE TITLE
GZIP index?

### ISSUE THREAD

**Issue by nybblr** [ember-cli-deploy/ember-cli-deploy-s3-index#27]
Loving the rearchitecture. One gotcha so far: I have the gzip plugin installed, but the index files don't get gzipped.

I don't really see any code that specifically excludes index.html from being gzipped, thoughts?

**Comment by lukemelia** [comment]
It's the filePattern config default that doesn't include .html

**Comment by lukemelia** [comment]
Glad you like 0.5.x!

**Comment by nybblr** [comment]
Thanks for the super-fast reply!

I updated the filePattern on the gzip plugin to include .html which worked, but I guess index.html is not getting uploaded with the Content-Encoding: gzip header so browsers see it as gobbledygook =)

**Comment by lukemelia** [comment]
s3-index likely needs to be updated to conditionally set this header.

**Comment by LevelbossMike** [comment]
Yes the plugin needs to be updated to work with gzipped html files correctly. I'll have time to look into this on friday the latest.

**Comment by LevelbossMike** [comment]
AWS added automatic gzipping to cloudfront does this fix what you want to do? @nybblr 

https://aws.amazon.com/de/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/

**Comment by nybblr** [comment]
Hmm, I don’t think I use CloudFront — I just host directly from S3, no CDNs.

**Comment by LevelbossMike** [comment]
ok. sorry that this takes so long. Haven't had much OSS time in the last few weeks due to holidays etc. will try to add a fix in the next few days
