### ISSUE TITLE
region should be required and not set by default

### ISSUE THREAD

**Issue by lukemelia** [ember-cli-deploy/ember-cli-deploy-s3-index#30]
This would make it similar to the s3 plugin, which made this change because users were having trouble diagnosing incorrect-region issues. I started to looking into implementing this myself, but can't see where the plugin is specifying region at all.

**Comment by LevelbossMike** [comment]
Thanks for this issue! Region is defined in the defaultConfig. I'll change that and make it similar to the s3 plugin.
