### ISSUE TITLE
AWS Credentials should not be required

### ISSUE THREAD

**Issue by quiddle** [ember-cli-deploy/ember-cli-deploy-s3-index#32]
Hard-coding AWS credentials is the least recommended option: 
1. Loaded from IAM roles for Amazon EC2 (if running on EC2),
2. Loaded from the shared credentials file (~/.aws/credentials),
3. Loaded from environment variables,
4. Loaded from a JSON file on disk,
5. Hardcoded in your application

By requiring the AWS Credentials, it prevents using these other methods.

The ember-cli-deploy-s3 plugin recently fixed this with [pull request 39](https://github.com/ember-cli-deploy/ember-cli-deploy-s3/pull/39).

~~I'm also fairly certain that if `region` is specified in a ~/.aws/config file, it will get picked up by the AWS SDK as well. Looking into that for sure.~~

**Comment by LevelbossMike** [comment]
Thx for this issue! This sounds like a useful change. Do you want to submit a PR for this?

**Comment by LevelbossMike** [comment]
Fixed via https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/pull/33 Thx again @quiddle
