### ISSUE TITLE
Latest release does not include AWS s3 improvements

### ISSUE THREAD

**Issue by sprockow** [ember-cli-deploy/ember-cli-deploy-s3-index#35]
ember-cli-deploy-s3 created an 0.2 release which allows the user to use iam profiles to upload files to s3, instead of explicitly passing in accessKey and secret params. 

This repo has also been updated to include that improvement as well. The documentation even says so. But a new release tag has not been created. I've pointed my package.json to the HEAD of master to resolve this. Is there a reason a release has not been created yet?

**Comment by lukemelia** [comment]
Too many holiday beers, and not enough OSS maintenance time :) Our release bot has been reminding us every night, and I'm sure we'll get this published very soon. I'll leave this open until we cut a new release. I'm glad you are finding value in the plugin.

**Comment by ghedamat** [comment]
@sprockow just released 0.2.0

https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/releases/tag/v0.2.0

feel free to test it! :)
