### ISSUE TITLE
NoSuchKey Error

### ISSUE THREAD

**Issue by eshtadc** [ember-cli-deploy/ember-cli-deploy-s3-index#58]
I'm getting the following in the verbose output 'NoSuchKey: The specified key does not exist.'
The credentials appear correct and the same values work in the ember-cli-deploy-s3 plugin.  I'm using this as part of the ember-cli-deploy-s3-pack plugin pack.  It did work once or twice and then I manually removed some files in the s3 bucket.  Is it possible that it is checking for the existence of a file first that has been removed?

Here is my deploy.js

``` javascript
module.exports = function(deployTarget) {
  var s3bucket = process.env.LIFT3_S3_BUCKET + '/' + appVersion + '/' + deployTarget;
  var ENV = {
    build: {},
    // include other plugin configuration that applies to all deploy targets here
    s3: {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      bucket: s3bucket,
      region: process.env.LIFT3_S3_BUCKET_REGION
    },
    's3-index': {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      bucket: s3bucket,
      region: process.env.LIFT3_S3_BUCKET_REGION,
      allowOverwrite: true,
    },
    activateOnDeploy: true,
  };

  return ENV;
};
```

The final line before the error:

> +- s3-index
> |    - preparing to upload revision to S3 bucket `lift3-us-east-1.decision-api.acquia.com/0.0.1/production`

Full didFail error:

> +- didFail
> NoSuchKey: The specified key does not exist.
> NoSuchKey: The specified key does not exist.
>     at Request.extractError (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/services/s3.js:327:35)
>     at Request.callListeners (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
>     at Request.emit (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>     at Request.emit (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/request.js:596:14)
>     at Request.transition (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/request.js:21:10)
>     at AcceptorStateMachine.runTo (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/state_machine.js:14:12)
>     at /Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/state_machine.js:26:10
>     at Request.<anonymous> (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/request.js:37:9)
>     at Request.<anonymous> (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/request.js:598:12)
>     at Request.callListeners (/Users/lisa.backer/Documents/workspace/lift/helios/lift3/node_modules/ember-cli-deploy-s3-pack/node_modules/ember-cli-deploy-s3-index/node_modules/aws-sdk/lib/sequential_executor.js:115:18)|
> Pipeline aborted

**Comment by lukemelia** [comment]
The ember-cli-deploy-s3-pack uses the manifest plugin which creates a text file with info from the last upload to avoid needing to check each file's existence independently and speed up the deploy. If you delete files under its nose, I suspect you would experience a problem like this one. You could try deleting the manifest file from S3. This should cause it to reupload everything.

**Comment by eshtadc** [comment]
That makes a lot of sense, but didn't appear to resolve the problem.  After looking at the config options more closely, though, I realized that I was setting the bucket to the full bucket (with the "prefix") included.  When I separated these two values then it worked as expected.  Gonna close this out as user error but thanks for such amazingly quick advice!

**Comment by lukemelia** [comment]
Glad you got it figured out @lkhaas!
