### ISSUE TITLE
No such file or directory, open '/index.html'

### ISSUE THREAD

**Issue by alexbeeken** [ember-cli-deploy/ember-cli-deploy-s3-index#61]
`Deploying [🚀 -] 75% [plugin: s3-index -> upload]Error: ENOENT: no such file or directory, open '/index.html'
Error: ENOENT: no such file or directory, open '/index.html'
    at Error (native)Pipeline aborted`

I was getting this error trying to deploy our company's ember app to staging. So, I decided to empty the buckets and create a fresh blank ember app to test if I still get this error 'out of the box'. Still happens. I use the same config. Here is my config file: 

```
module.exports = function(environment) {
  var ENV = {};

  if (environment === 'staging') {
    ENV.plugins = ['s3', 's3-index'];
    ENV.build = {
      environment: 'staging',
    };

    ENV['s3-index'] = {
      accessKeyId: '<removed>',
      secretAccessKey: '<removed>',
      bucket: 'bucket-name',
      region: 'us-west-2'
    };

    ENV.s3 = {
      gzip: true,
      accessKeyId: '<removed>',
      secretAccessKey: '<removed>',
      region: 'us-west-2',
      bucket: 'bucket-name-assets'
    }
  }
  return ENV;
};
```

**Comment by LevelbossMike** [comment]
are you using the [build plugin](https://www.npmjs.com/package/ember-cli-deploy-build) that takes care of building your project?

**Comment by alexbeeken** [comment]
Yeah but is having it installed enough to take care of the build process? I can't find anything in the docs to say otherwise. It seems to not work even if I run ember build or anything else.

**Comment by alexbeeken** [comment]
Aha, you were right. It looks like the problem was that I didn't have the `build` package inside my `ENV.plugins = ['s3', 's3-index', 'build'];` line in my config. Even thought I had the package installed, I didn't think to put it in the plugins array.

**Comment by LevelbossMike** [comment]
You don't have to use the plugins array unless you want to specify that plugins don't run in some environments, you want to alias plugins or you want to change the order in which plugins run. When you don't specify the plugins setting everything should work as expected for most use cases. That's an advanced setting which I suggest you don't use in your `deploy.js`-file unless you have the explicit need to.
