### ISSUE TITLE
Full Changelog link is not working (minor error)

### ISSUE THREAD

**Issue by urbany** [ember-cli-deploy/ember-cli-deploy-s3-index#65]
Hi, first of all great plugin and thanks so much for keeping an updated changelog it's very helpful.
I noticed inside CHANGELOG.md there is a _Full Changelog_ link for each release. This is a good idea. There's just a minor bug that is preventing the link from working, the last tag is missing a _v_ before the tag name.

Current not working:
https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/compare/v0.4.0...0.5.0

Should be
https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/compare/v0.4.0...v0.5.0

**Comment by ghedamat** [comment]
thanks for the report @urbany!  should be fixed now

**Comment by urbany** [comment]
Great! This seems to be happening in the other CHANGELOG.md files also - https://github.com/ember-cli-deploy/ember-cli-deploy/blob/master/CHANGELOG.md - might want to check the script that generates those.

**Comment by ghedamat** [comment]
yeah, I think we switched to a new one and there might be a setting missing
if you have time to open a few PRs it's definitely appreciated! (not pressure though :P) 

/cc @lukemelia 

p.s
if you do please prefix the commits with `[DOC]`

thanks again!
