### ISSUE TITLE
Deprecation warning with ember-cli 2.12.0

### ISSUE THREAD

**Issue by elgordino** [ember-cli-deploy/ember-cli-deploy-s3-index#70]
With ember-cli-2.12.0 I am seeing this deprecation warning when running ember commands

    DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
    Object.<anonymous> (/Users/gordonj/git/ninja-prototype/node_modules/ember-cli-deploy-s3-index/lib/s3.js:6:23)

This is with ember-cli-deploy-s3-index 0.5.0

**Comment by lukemelia** [comment]
@elgordino fix released in 1.0.0.beta.0. Can you verify this addresses the issue for you?

**Comment by elgordino** [comment]
Works a treat thanks. I've also updated with your other updates which are working fine for me too :)

    "ember-cli-deploy-build": "1.0.0-beta.0",
    "ember-cli-deploy-display-revisions": "1.0.0-beta.0",
    "ember-cli-deploy-revision-data": "1.0.0-beta.0",
    "ember-cli-deploy-s3": "1.0.0-beta.0",
    "ember-cli-deploy-s3-index": "1.0.0-beta.0",
