### ISSUE TITLE
The support for `profile` is not released :(

### ISSUE THREAD

**Issue by denzo** [ember-cli-deploy/ember-cli-deploy-s3-index#76]
The amazing support for `profile` has not been released.
https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/blob/master/lib/s3.js#L36

Maybe there's a reason I'm not aware of, otherwise if you have a spare second would you be so kind to release it?

Let me know if I could assist in any way.

**Comment by LevelbossMike** [comment]
Hi! Thanks for reporitng this. I'll create a release today

**Comment by LevelbossMike** [comment]
@denzo released with  725cdac
