### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lukemelia** [ember-cli-deploy/ember-cli-deploy-s3-index#93]
@LevelbossMike I updated a bunch of dependencies and am ready to cut a new release. Just wanted to make sure you were on board before I did so.

**Comment by LevelbossMike** [comment]
@lukemelia thanks and sure! Sounds good to me 👍

**Comment by lukemelia** [comment]
1.1.0 has been released 🎉

**Comment by LevelbossMike** [comment]
Thanks @lukemelia 👏
